### ISSUE TITLE
map-to-xml fails when mapfile contains a LIKE filter.

### ISSUE THREAD

**Issue by archaeogeek** [AstunTechnology/mapserver-upgrade-config#12]
Related to this upstream issue: https://github.com/geographika/mappyfile/issues/37

A filter clause of the form `FILTER ("blpu_classification_code" LIKE 'RI%')` will cause map-to-xml to fail with the following error:

> (mapserver-upgrade-config) E:\iShareData\LIVE\_MapServerConfig>map-to-xml corpor
ate.map -o xml\corporate.xml
Processing corporate.map
ERROR:mappyfile:Parsing of Mapfile unsuccessful
Traceback (most recent call last):
  File "D:\Astun\Tools\mapserver-upgrade-config\Scripts\map-to-xml-script.py", l
ine 11, in <module>
    load_entry_point('mapfile-utils==1.0.2', 'console_scripts', 'map-to-xml')()
  File "D:\Astun\Tools\mapserver-upgrade-config\maputils\map_to_xml.py", line 38
8, in main
    mapper = map_to_xml(args.inputfile,  output_file=args.outputfile)
  File "D:\Astun\Tools\mapserver-upgrade-config\maputils\map_to_xml.py", line 33
2, in __init__
    mapp = mappyfile.utils.load(self.input)
  File "D:\Astun\Tools\mapserver-upgrade-config\lib\site-packages\mappyfile-0.7.
1a0-py2.7.egg\mappyfile\utils.py", line 65, in load
    ast = p.load(fp)
  File "D:\Astun\Tools\mapserver-upgrade-config\lib\site-packages\mappyfile-0.7.
1a0-py2.7.egg\mappyfile\parser.py", line 163, in load
    return self.parse(text)
  File "D:\Astun\Tools\mapserver-upgrade-config\lib\site-packages\mappyfile-0.7.
1a0-py2.7.egg\mappyfile\parser.py", line 189, in parse
    tree = self.lalr.parse(text)
  File "D:\Astun\Tools\mapserver-upgrade-config\lib\site-packages\lark_parser-0.
5.6-py2.7.egg\lark\lark.py", line 197, in parse
    return self.parser.parse(text)
  File "D:\Astun\Tools\mapserver-upgrade-config\lib\site-packages\lark_parser-0.
5.6-py2.7.egg\lark\parser_frontends.py", line 47, in parse
    return self.parser.parse(token_stream, self.lexer.set_parser_state)
  File "D:\Astun\Tools\mapserver-upgrade-config\lib\site-packages\lark_parser-0.
5.6-py2.7.egg\lark\parsers\lalr_parser.py", line 71, in parse
    action, arg = get_action(token.type)
  File "D:\Astun\Tools\mapserver-upgrade-config\lib\site-packages\lark_parser-0.
5.6-py2.7.egg\lark\parsers\lalr_parser.py", line 50, in get_action
    raise UnexpectedToken(token, expected, seq, i)
lark.common.UnexpectedToken: Unexpected token Token(UNQUOTED_STRING, u'LIKE') at
 line 6960, column 37.
Expected: ['__EQUAL', '__LESSTHAN', u'__NE21', '__ANONSTR_19', u'__GE25', '__STA
R', u'__GT26', '__ANONSTR_13', u'__EQ22', u'__LE23', '__ANONSTR_16', '__SLASH',
'__ANONSTR_14', '__PLUS', '__ANONSTR_17', '__MINUS', '__ANONSTR_11', '__ANONSTR_
15', u'__LT24', '__TILDE', u'__OR10', '__MORETHAN', '__CIRCUMFLEX', '__RPAR', u'
__AND12', u'__IN20', '__ANONSTR_18']
Context: <no context>

**Comment by archaeogeek** [comment]
[corporate.zip](https://github.com/AstunTechnology/mapserver-upgrade-config/files/3064065/corporate.zip)
